### ISSUE TITLE
Hello I wanted to get in touch, before I do something ..

### ISSUE THREAD

**Issue by sabinem** [timster/peewee-validates#1]
I am looking for an opportunity to start contributing to an open source project and I chose you project, because I like it, I understand it and there might be something to help out on. As a first task, I decided to remove the print statement: there is one in your code, that I think is not supposed to be there. I forked the repo and deleted the statement in a new branch, I will send you a pull request, if you do not mind and I would also don't mind to put the docu into Spinx for you as a next try to contribute something.
This is the print statement in your code: 
def validate_required():
    def required_validator(field, data):
        print('checking', field.name, 'with', data, 'and', field.value)
        if not field.value:
            raise ValidationError('required')
    return required_validator

I am sure you can easily fix this yourself, but would you mind, if I send you my pull request? I feel like a newbie to open source and hope I am doing things right to get started, otherwise, please tell me.

**Comment by timster** [comment]
Hi! Thanks for the message. Please do feel free to send a pull request if you'd like. That print statement was in there for debugging purposes.

**Comment by timster** [comment]
Closed by #2
